### ISSUE TITLE
Why is signin needed?

### ISSUE THREAD

**Issue by ThatOneCalculator** [LivreBooks/livre#5]
Generally, library genesis can be accessed without an account. Why do you need to sign in with Google to use this client?

**Comment by Patrick-web** [comment]
It's for planned features. Like for example in the account tab, you can see your past downloads when you switch devices and I will be adding a button to re-download them. tldr To restore data (downloads, reading progress, and possibly personalized recommendations).

If you don't want to sign in you can long-press the name Livre on the sign-in page to skip it.

**Comment by ThatOneCalculator** [comment]
There should be a very clear "skip login" button imo, as nobody would know that without looking up this issue.

**Comment by Patrick-web** [comment]
I agree. I'll add it in the next release.

**Comment by Patrick-web** [comment]
I agree. I'll add it in the next release.
